### Admin Registration
POST http://127.0.0.1:8000/api/admin/register/
Content-Type: application/json

{
    "institutionName": "Vignan University",
    "institutionCode": "VIGNAN001",
    "name": "Vignan University",
    "db_uri": "vignan_db_uri",
    "admin_email": "info@vignan.ac.in",
    "contactEmail": "admin@vignan.ac.in",
    "contactPhone": "+91-9876543210",
    "password": "SecurePass123!",
    "logo_url": "https://admissions-ui.vercel.app/assets/img/Logo%20with%20Deemed.svg",
    "address": "Vadlamudi, Guntur, Andhra Pradesh, India",
    "settings": {
        "timezone": "Asia/Kolkata",
        "language": "en",
        "enableRegistration": true,
        "maxUsers": 10000
    }
}

### Get the Admin Details
GET http://127.0.0.1:8000/api/admin/details/?admin_email=info@test.ac.in

### Admin Password with update with email
PUT http://127.0.0.1:8000/api/admin/password-reset/
Content-Type: application/json

{
    "admin_email": "info@test.ac.in",
    "new_password": "Chari@6268"
}

### Admin Login
POST http://127.0.0.1:8000/api/admin/login/
Content-Type: application/json

{
    "email": "info@vignan.ac.in",
    "password": "NewSecurePass456!"
}
