# REST tests for exam schedule check
# Usage: Install the REST Client extension in VS Code and send the requests.

@host = http://localhost:8000/api

### Check exam schedule by from date to date
GET {{host}}/applications/?examFromDate=2025-10-20&examToDate=2026-04-30
Accept: application/json

### Check exam schedule by MongoDB ObjectId
GET {{host}}/applications/?examDate=2026-04-10&examSlot=11:00
Accept: application/json


###
GET {{host}}/applications/payments/

### Check exam schedule by generated student_id
# Example generated student id: VU25HYD000001
GET {{host}}/applications/?student_id=VU25HYD000001&examDate=2025-10-25
Accept: application/json


### Check exam schedule by email
GET {{host}}/applications/?email=test.student@example.com&examDate=2025-11-15&examSlot=09:00-11:00
Accept: application/json


### Get full application detail by student_id (Mongo ObjectId)
GET {{host}}/applications/?student_id=64f3a1b2c3d4e5f678901234
Accept: application/json


### Get full application detail by generated student_id
GET {{host}}/applications/student-id/VU25HYD000001/
Accept: application/json


### Get full application detail by email
GET {{host}}/applications/?email=test.student@example.com
Accept: application/json
