### Test Send OTP
POST https://18.60.253.120/api/send-otp/
Content-Type: application/json

{
  "phone": "8978083533"
}

###
POST https://admissions-back-end.vercel.app/api/send-otp/
Content-Type: application/json

{
  "phone": "8978083533"
}

###
POST https://admissions-back-end.vercel.app/api/verify-otp/
Content-Type: application/json

{
  "phone": "8978083533",
  "otp": "123456"
}

###
POST https://admissions-back-end-git-auth-chari6268s-projects.vercel.app/api/send-otp/
Content-Type: application/json

{
  "phone": "8978083533"
}

### Test Verify OTP
POST http://127.0.0.1:8000/api/verify-otp/
Content-Type: application/json

{
  "phone": "9873216540",
  "otp": "263564"
}


###
POST http://127.0.0.1:8000/api/otpbase-login/
Content-Type: application/json

{
  "phone": "9873216540",
  "otp": "263564"
}